apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      tier: backend

  template:
    metadata:
      labels:
        app: demo
        tier: backend
        app.kubernetes.io/name: backend
    spec:
      containers:
      - name: json-mock
        image: quay.io/cilium/json-mock

---
apiVersion: v1
kind: Service
metadata:
  name: backend 
  labels:
    app.kubernetes.io/name: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: demo
    tier: backend

---
