apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app.kubernetes.io/name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      tier: database

  template:
    metadata:
      labels:
        app: demo
        tier: database
        app.kubernetes.io/name: database
    spec:
      containers:
      - name: redis
        image:  docker.io/nicolas/webdis:0.1.22
---

apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app.kubernetes.io/name: database
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7379
  selector:
    app: demo
    tier: database


