apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      tier: frontend

  template:
    metadata:
      labels:
        app: demo
        tier: frontend
        app.kubernetes.io/name: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
  type: NodePort
  selector: 
    app: demo
  ports:
   - protocol: UDP
     port: 12345 # port internal to cluster
     targetPort: 12345 # port where the app listens
     nodePort: 32000 # externally visible port
  selector:
    app: demo
    tier: frontend


