apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      tier: frontend

  template:
    metadata:
      labels:
        app: demo
        tier: frontend
        app.kubernetes.io/name: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: demo
    tier: frontend
  type: NodePort
  selector:
    app: demo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
