
---
apiVersion: v1
kind: Namespace
metadata:
 name: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-ebpf
  namespace: monitoring
  labels:
    app: kube-ebpf
spec:
  selector:
    matchLabels:
      name: kube-ebpf
  template:
    metadata:
      labels:
        name: kube-ebpf
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/'
        prometheus.io/port: '8000'
    spec:
      containers:
        - name: flow-tracer-ctr
          image: flow-tracer:1.0
          ports:
            - containerPort: 8000
              name: metrics
          imagePullPolicy: Never
          resources:
            requests:
              ephemeral-storage: "2Gi"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PYTHONUNBUFFERED
              value: "1"
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: debug
              mountPath: /sys/kernel/debug
              readOnly: false
            - name: sysfsbpf
              mountPath: /sys/fs/bpf
              readOnly: false
      hostNetwork: true
      hostPID: true
      serviceAccountName: kube-ebpf
      volumes:
        - name: modules-dir
          hostPath:
            path: /lib/modules
        - name: debug
          hostPath:
            path: /sys/kernel/debug
        - name: sysfsbpf
          hostPath:
            path: /sys/fs/bpf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-ebpf
rules:
  - apiGroups: [""]
    resources:
      - services
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-ebpf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ebpf
subjects:
  - kind: ServiceAccount
    name: kube-ebpf
    namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ebpf
  namespace: monitoring
