
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: icmp-blocker-xdp
  labels:
    app: icmp-blocker-xdp
spec:
  selector:
    matchLabels:
      name: icmp-blocker-xdp
  template:
    metadata:
      labels:
        name: icmp-blocker-xdp
    spec:
      containers:
        - name: icmp-blocker-xdp
          image: icmp-blocker:1.0
          imagePullPolicy: Never # always pull from local microk8s repo; without this line, it will connect to dockerhub
          securityContext:
            privileged: true # run ctr in privileged mode for bpf programs to execute
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: debuglog
              mountPath: /sys/kernel/debug
            - name: sysfsbpf
              mountPath: /sys/fs/bpf
            - name: libmodules
              mountPath: /lib/modules
              # insert run cmd if you wish to
      volumes:
        - name: varlog
          hostPath:
            path: /var/log # generic kernel logs 
        - name: debuglog
          hostPath:
            path: /sys/kernel/debug # this is needed for tracing
        - name: sysfsbpf
          hostPath:
            path: /sys/fs/bpf # bpf programs mounted here
        - name: libmodules
          hostPath:
            path: /lib/modules # for common kernel headers shared between ctr and host

